SELECT*FROM Customers
ORDER BY CustState, CustCity;


SELECT DISTINCT P1.PRODUCTNUMBER
FROM Categories C INNER JOIN Products P
ON P1.PRODUCTNUMBER = P2.PRODUCTNUMBER
WHERE P1.VENDORID <> P2.VENDORID
ORDER BY P1.PRODUCTNUMBER;


SELECT o.ordersid
FROM orders o INNER JOIN PRODUCT_VENDORS PV 
ON P.PRODUCTNUMBER = PV.PRODUCTNUMBER
INNER JOIN VENDORS V ON PV.VENDORID = V.VENDORID
ORDER BY VENDNAME, PRODUCTNAME;


/*Return the OrderId  and ContactName (from the customer table) for each order sold by employee 5  
*/

SELECT Orderid
FROM Orders 
INNER JOIN Customers
ON Orders.ORDERID= ORDERS.CONTACTNAME
AND Contactname=5;

FROM CUSTOMERS
 INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
AND ORDERNUMBER=806;

SELECT CustFirstName, CustLastName, ShipDate
FROM CUSTOMERS
 INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
AND ORDERNUMBER=806;

SELECT ORDERID, ContractName
FROM CUSTOMERS
INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID
AND EMPLOYEE=5;

SELECT PRODUCTNAME, VENDNAME
FROM PRODUCTS P INNER JOIN PRODUCT_VENDORS PV 
ON P.PRODUCTNUMBER = PV.PRODUCTNUMBER
INNER JOIN VENDORS V ON PV.VENDORID = V.VENDORID
ORDER BY VENDNAME, PRODUCTNAME;


SELECT productname, proctprice
FROM Products p INNER JOIN PRODUCTS P
ON C.CATEGORYID=P.CATEGORYID
ORDER BY  AND CATEGORYNAME desc ;

select 

SELECT CATEGORY 

SELECT*FROM Customers
ORDER BY COUNTRY,City;


/*INSERT INTO Products(ProductID, ProductName, SupplierID, CategoryID, 
QuantityPerUnit, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel, Discontinued) 
VALUES (78, 'Super Frankfurter', 95, 7, '12 boxes', 13.0000, 32, 0, 15, 0)*/

DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
   
       CREATE TABLE PRODUCTS
       (
       PRODUCTID         NUMBER (8, 0) NOT NULL,
       PRODUCTNAME      VARCHAR2 (40) NOT NULL,
       SUPPLIERID         NUMBER (8, 0),
       CATEGORYID        NUMBER (8, 0),
       QUANTITYPERUNIT   VARCHAR2 (20),
       UNITPRICE           NUMBER (8, 2),
       UNITSINSTOCK       NUMBER (6, 0),
       UNITSONORDER       NUMBER (6, 0),
       REORDERLEVEL       NUMBER (6, 0),
       DISCONTINUED       NUMBER (1, 0) NOT NULL,
      CONSTRAINT products_PRODUCTID_pk PRIMARY KEY (PRODUCTID),
      CONSTRAINT PRODUCTS_SUPPLIERS_FK FOREIGN KEY (SUPPLIERID)
      REFERENCES SUPPLIERS(SUPPLIERID),
      CONSTRAINT PRODUCTS_CATEGORIES_FK FOREIGN KEY(CATEGORYID)
      REFERENCES CATEGORIES(CATEGORYID),
      CONSTRAINT PRODUCTS_UNITPRICE_CK CHECK(UNITPRICE>=0),
      CONSTRAINT PRODUCTS_REORDERLEVEL_CK CHECK(REORDERLEVEL>=0),
      CONSTRAINT PRODUCTS_UNITSINSTOCK_CK CHECK(UNITSINSTOCK>=0),
      CONSTRAINT PRODUCTS_UNITSONORDER_CK CHECK(UNITSONORDER>=0)
     );
 INNSERT PRODUCTS(ProductID, ProductName, SupplierID, CategoryID, 
QuantityPerUnit, UnitPrice, UnitsInStock, UnitsOnOrder, ReorderLevel, Discontinued)
VALUES
(78, 'Super Frankfurter', 95, 7, '12 boxes', 13.0000, 32, 0, 15, 0);